Report new Python warnings in CI builds
Makes changes such that, after the CI runs on a PR, a comment is made on
the PR that lists any new warnings. New warnings do not fail the build,
these are just notifications.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,13 +101,69 @@ jobs:
     - name: Run pytest bluemira
       shell: bash -l {0}
       env:
+        # Flag to run longrun tests when merging dependency updates
         # https://github.com/actions/runner/issues/409#issuecomment-752775072
-        PYTEST_LONGRUN: ${{ github.ref_name == "develop_dependencies" && "--longrun" || "" }}
+        PYTEST_LONGRUN: ${{ github.event.pull_request.head == "develop_dependencies" && "--longrun" || "" }}
       run: |
         pytest --cov=bluemira \
                --cov-report html:htmlcov_bluemira \
                --cov-report xml \
+               --json-report \
+               --json-report-indent=3 \
                tests examples/design/EU-DEMO --reactor --private ${PYTEST_LONGRUN}
+
+    - name: Upload test report (push only)
+      if: ${{ github.event_name == 'push' }}
+      uses: actions/upload-artifact@v3
+      with:
+        name: report-json
+        path: .report.json
+
+    - name: Download reference test report (PR only)
+      if: ${{ github.event_name == 'pull_request' }}
+      # Do not fail if the report is not found. It may not exist if the
+      # artifact has expired, or there is a build of develop in progress.
+      # In case we don't find an old report, we just report all the warnings.
+      continue-on-error: true
+      uses: dawidd6/action-download-artifact@v2
+      with:
+        workflow: ci.yml
+        name: report-json
+        commit: ${{ github.event.pull_request.ref.sha }}
+        path: ref_report
+        search_artifacts: true
+
+    - name: Generate warning report
+      if: ${{ github.event_name == 'pull_request' }}
+      id: warning-report
+      run: |
+        if [ -f "ref_report/.report.json" ]; then
+          compare_args="--compare ref_report/.report.json"
+        fi
+        report_str=$(python scripts/format_warning_report.py .report.json ${compare_args}) || true
+        # Ugly stuff to escape new lines
+        report_str="${report_str//'%'/'%25'}"
+        report_str="${report_str//$'\n'/'%0A'}"
+        echo "::set-output name=report::"${report_str}""
+
+    - name: Find warning report comment
+      if: ${{ github.event_name == 'pull_request' }}
+      uses: peter-evans/find-comment@v2
+      id: find-warning-report-comment
+      with:
+        issue-number: ${{ github.event.pull_request.number }}
+        comment-author: "github-actions[bot]"
+        body-includes: ⚠️ Warning Report
+        direction: last
+
+    - name: Create or update warning report comment
+      if: ${{ github.event_name == 'pull_request' }}
+      uses: peter-evans/create-or-update-comment@v2
+      with:
+        comment-id: ${{ steps.find-warning-report-comment.outputs.comment-id }}
+        issue-number: ${{ github.event.pull_request.number }}
+        body: ${{ steps.warning-report.outputs.report }}
+        edit-mode: replace
 
     - name: "Upload coverage to Codecov"
       uses: codecov/codecov-action@v2
